
export enum Actions {
    OPEN_LINK,
    UPDATE_REQUEST_VALUE,
    UPDATE_REQUEST_HEADER,
    NEW_REQUEST,
    NEW_REQUEST_PROPERTY,
    NEW_REQUEST_HEADER,
    DELETE_REQUEST_PROPERTY,
    DELETE_REQUEST_HEADER,
    RESEND_CAPTURED_REQUEST,
    DELETE_CAPTURED_REQUEST,
    COPY_CAPTURED_REQUEST,
    NEW_FORM_PARAMETER,
    DELETE_FORM_PARAMETER,
    UPDATE_FORM_PARAMETER,
    SUBMIT_FORM,
    REFRESH,
    DOS_ATTACK
}

export enum PageCommands {
    UPDATE,
    START,
    STOP,
    SUBMIT
}